import { readFile, writeFile, mkdir, chmod } from "node:fs/promises";
import { join } from "node:path";
import chalk from "chalk";
import { fileExists } from "../utils/fs.js";

interface HookConfig {
  hooks: {
    PreCommit?: HookEntry[];
    PostCommit?: HookEntry[];
  };
}

interface HookEntry {
  matcher: string;
  command: string;
}


export async function setupHooks(root: string): Promise<void> {
  await setupClaudeHooks(root);
  await setupClaudeSettings(root);
  await setupGitHooks(root);
}


// Stale sets hold commands grimoire installed in past releases; update
// upgrades them in place. Exact-match only — customized variants stay untouched.
const CURRENT_CLAUDE_CHECK = "grimoire check lint format doc_style --changed --json";
const STALE_CLAUDE_CHECKS = new Set([
  "grimoire check --changed --json",
  "grimoire check --changed --json --skip best_practices",
]);
const CURRENT_GIT_CHECK = "grimoire check lint format doc_style --changed";
const STALE_GIT_CHECKS = new Map([
  ["grimoire check --changed", CURRENT_GIT_CHECK],
  ["grimoire check --changed --skip best_practices", CURRENT_GIT_CHECK],
  [
    "node bin/grimoire.js check --changed --skip best_practices",
    "node bin/grimoire.js check lint format doc_style --changed",
  ],
]);
const LEGACY_GATE_PREFIX = "grimoire check --changed";

async function setupClaudeHooks(root: string): Promise<void> {
  const claudeDir = join(root, ".claude");
  const hooksPath = join(claudeDir, "hooks.json");

  const hooks: HookConfig = {
    hooks: {
      PreCommit: [
        {
          matcher: "*",
          // Keep save-time feedback mechanical and cheap. Final verification
          // owns broad checks and configured test suites.
          command: CURRENT_CLAUDE_CHECK,
        },
      ],
      PostCommit: [
        {
          matcher: "*",
          command: trailerCheckScript(),
        },
      ],
    },
  };

  await mkdir(claudeDir, { recursive: true });

  if (await fileExists(hooksPath)) {
    // Merge with existing hooks — don't overwrite user config
    try {
      const existing = JSON.parse(await readFile(hooksPath, "utf-8")) as HookConfig;
      const merged = mergeHooks(existing, hooks);
      await writeFile(hooksPath, JSON.stringify(merged, null, 2) + "\n");
      console.log(`  ${chalk.blue("merged")}  .claude/hooks.json`);
    } catch {
      // Existing file is malformed — back it up and replace
      await writeFile(hooksPath + ".bak", await readFile(hooksPath, "utf-8"));
      await writeFile(hooksPath, JSON.stringify(hooks, null, 2) + "\n");
      console.log(`  ${chalk.yellow("replaced")} .claude/hooks.json (old file backed up)`);
    }
  } else {
    await writeFile(hooksPath, JSON.stringify(hooks, null, 2) + "\n");
    console.log(`  ${chalk.green("created")} .claude/hooks.json`);
  }
}


// Substitutes stale grimoire check lines in place — never deletes a line, so
// surrounding shell structure (if/fi blocks) can never be broken.
function upgradeStaleGitLines(existing: string): string | null {
  const lines = existing.split("\n");
  if (!lines.some((line) => STALE_GIT_CHECKS.has(line.trim()))) return null;

  const updated = lines.map((line) => {
    const replacement = STALE_GIT_CHECKS.get(line.trim());
    return replacement === undefined
      ? line
      : (line.match(/^\s*/)?.[0] ?? "") + replacement;
  });
  return updated.join("\n");
}

async function setupGitHooks(root: string): Promise<void> {
  const gitHooksDir = join(root, ".git", "hooks");

  // Only create if .git exists (this is a git repo)
  if (!(await fileExists(join(root, ".git")))) return;

  const preCommitPath = join(gitHooksDir, "pre-commit");

  // Don't overwrite existing hooks
  if (await fileExists(preCommitPath)) {
    const existing = await readFile(preCommitPath, "utf-8");

    const upgraded = upgradeStaleGitLines(existing);
    if (upgraded !== null) {
      await writeFile(preCommitPath, upgraded);
      console.log(`  ${chalk.blue("updated")} .git/hooks/pre-commit (stale grimoire check upgraded)`);
      return;
    }

    if (existing.includes("grimoire check")) {
      console.log(
        `  ${chalk.yellow("exists")}  .git/hooks/pre-commit (has a grimoire check; current command: ${CURRENT_GIT_CHECK})`
      );
      return;
    }
    // Check if existing hook has exit/exec that would prevent our code from running
    if (/^[^#]*\b(exit\s|exec\s)/m.test(existing)) {
      console.log(`  ${chalk.yellow("manual")}  .git/hooks/pre-commit contains exit/exec — add manually: ${CURRENT_GIT_CHECK}`);
      return;
    }
    // Append grimoire check to existing hook
    const appended = existing.trimEnd() + "\n\n# Grimoire pre-commit checks\n" + CURRENT_GIT_CHECK + "\n";
    await writeFile(preCommitPath, appended);
    console.log(`  ${chalk.blue("appended")} .git/hooks/pre-commit`);
    return;
  }

  await mkdir(gitHooksDir, { recursive: true });

  const hookScript = `#!/bin/sh
# Grimoire pre-commit checks
# Generated by grimoire init — safe to customize

# Fast writing checks only. Final verification owns broad checks and test suites.
if command -v grimoire >/dev/null 2>&1; then
  ${CURRENT_GIT_CHECK}
fi
`;

  await writeFile(preCommitPath, hookScript);
  await chmod(preCommitPath, 0o755);
  console.log(`  ${chalk.green("created")} .git/hooks/pre-commit`);
}


interface ClaudeSettings {
  hooks?: Record<string, ClaudeHookEntry[]>;
  [key: string]: unknown;
}

interface ClaudeHookEntry {
  matcher?: string;
  hooks: Array<{ type: string; command: string }>;
}

const BRANCH_GUARD_COMMAND = "grimoire branch-check --hook";
const BRANCH_GUARD_MARKER = "grimoire branch-check";
const COMMENT_LINT_COMMAND = "grimoire lint-comments --hook";
const COMMENT_LINT_MARKER = "grimoire lint-comments";

/** True if any entry already wires a command containing `marker`. */
function hasHook(entries: ClaudeHookEntry[], marker: string): boolean {
  return entries.some((entry) => entry.hooks?.some((h) => h.command?.includes(marker)));
}

interface LoadedSettings {
  settings: ClaudeSettings;
  existed: boolean;
  wasMalformed: boolean;
}

async function readClaudeSettings(settingsPath: string): Promise<LoadedSettings> {
  if (!(await fileExists(settingsPath))) {
    return { settings: {}, existed: false, wasMalformed: false };
  }
  const raw = await readFile(settingsPath, "utf-8");
  try {
    return { settings: JSON.parse(raw) as ClaudeSettings, existed: true, wasMalformed: false };
  } catch {
    await writeFile(settingsPath + ".bak", raw);
    return { settings: {}, existed: true, wasMalformed: true };
  }
}

function logSettings(existed: boolean, wasMalformed: boolean): void {
  const verb = !existed ? "created" : wasMalformed ? "replaced" : "updated";
  const color = verb === "created" ? "green" : verb === "replaced" ? "yellow" : "blue";
  console.log(`  ${chalk[color](verb)} .claude/settings.json (branch-check + comment-lint hooks)`);
}

async function setupClaudeSettings(root: string): Promise<void> {
  const settingsPath = join(root, ".claude", "settings.json");
  const { settings, existed, wasMalformed } = await readClaudeSettings(settingsPath);

  const hooks = settings.hooks ?? {};
  const userPromptSubmit = hooks.UserPromptSubmit ?? [];
  const preToolUse = hooks.PreToolUse ?? [];

  let changed = false;
  if (!hasHook(userPromptSubmit, BRANCH_GUARD_MARKER)) {
    userPromptSubmit.push({ hooks: [{ type: "command", command: BRANCH_GUARD_COMMAND }] });
    changed = true;
  }
  if (!hasHook(preToolUse, COMMENT_LINT_MARKER)) {
    preToolUse.push({ matcher: "Write|Edit", hooks: [{ type: "command", command: COMMENT_LINT_COMMAND }] });
    changed = true;
  }

  if (!changed) {
    console.log(`  ${chalk.yellow("exists")}  .claude/settings.json (branch-check + comment-lint hooks)`);
    return;
  }

  hooks.UserPromptSubmit = userPromptSubmit;
  hooks.PreToolUse = preToolUse;
  settings.hooks = hooks;

  await mkdir(join(root, ".claude"), { recursive: true });
  await writeFile(settingsPath, JSON.stringify(settings, null, 2) + "\n");
  logSettings(existed, wasMalformed);
}

function trailerCheckScript(): string {
  // Inline shell command that checks for Change: trailer
  // Only enforces when there are active grimoire changes
  return `sh -c 'if [ -d .grimoire/changes ] && [ "$(ls -A .grimoire/changes 2>/dev/null)" ]; then TRAILER=$(git log -1 --format="%(trailers:key=Change)" 2>/dev/null); if [ -z "$TRAILER" ]; then echo "WARNING: Commit is missing Change: trailer. Active grimoire changes exist."; fi; fi'`;
}

// Entry commands come from a user-edited file, so read them defensively.
function commandOf(entry: { command?: unknown }): string {
  return typeof entry.command === "string" ? entry.command : "";
}

// Grimoire-owned check entries collapse to one, upgraded to the current
// command; every other entry passes through untouched, as do foreign phases.
function mergeHooks(existing: HookConfig, additions: HookConfig): HookConfig {
  const merged: HookConfig = { hooks: { ...(existing.hooks ?? {}) } };

  for (const [phase, entries] of Object.entries(additions.hooks)) {
    const key = phase as keyof HookConfig["hooks"];
    const raw = merged.hooks[key];
    if (raw !== undefined && !Array.isArray(raw)) continue;
    const existingEntries = raw ?? [];
    const newEntries = entries ?? [];

    const owned = (e: { command?: unknown }) =>
      commandOf(e) === CURRENT_CLAUDE_CHECK || STALE_CLAUDE_CHECKS.has(commandOf(e));
    const foreign = existingEntries.filter((e) => !owned(e));
    const ownedEntries = existingEntries.filter(owned);

    // Prefer the wildcard matcher so check coverage never narrows.
    const kept = ownedEntries.find((e) => e.matcher === "*") ?? ownedEntries[0];
    const upgraded = kept ? [{ ...kept, command: CURRENT_CLAUDE_CHECK }] : [];

    // A customized gate variant occupies the grimoire slot; do not stack the
    // stock command next to it. Unrelated grimoire commands are not gates.
    const present = [...foreign, ...upgraded];
    const commands = new Set(present.map(commandOf));
    const hasGate = present.some((e) => {
      const command = commandOf(e);
      return command === CURRENT_CLAUDE_CHECK || command.startsWith(LEGACY_GATE_PREFIX);
    });
    const toAdd = newEntries.filter(
      (e) =>
        !commands.has(commandOf(e)) &&
        !(commandOf(e) === CURRENT_CLAUDE_CHECK && hasGate)
    );

    merged.hooks[key] = [...foreign, ...upgraded, ...toAdd];
  }

  return merged;
}
