import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtemp, mkdir, readFile, writeFile, rm } from "node:fs/promises";
import { existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { basename, join } from "node:path";
import { parse as parseYaml } from "yaml";
import { buildSite } from "./site.js";
import type { GrimoireConfig } from "../utils/config.js";

const OVERVIEW = `# test-project

> Auto-generated by \`grimoire docs\` — 2026-08-21.

## Capabilities
`;

const FEATURE = `Feature: User login
  Scenario: Successful login
    Given valid credentials
    When I submit the form
    Then I am logged in
`;

const ACCEPTED_DECISION = `---
status: accepted
date: 2026-01-01
---

# Use the example approach

## Context and Problem Statement
We needed an example.

## Decision Outcome
Chosen option: "example", because it is illustrative.
`;

const PROPOSED_DECISION = `---
status: proposed
date: 2026-02-01
---

# Try the other approach

## Context and Problem Statement
An alternative.
`;

const CONSTRAINTS = `# Constraints
| Constraint (assertion) | Rationale | How verified | Links |
|---|---|---|---|
| Logs never contain PII | confidential data | tests/test_logs.py | ADR-0008 |
`;

function configWith(command?: string): GrimoireConfig {
  return {
    version: 3,
    project: { commit_style: "conventional" },
    features_dir: "features",
    decisions_dir: ".grimoire/decisions",
    tools: command ? { spec_site: { name: "stub", command } } : {},
    checks: [],
    llm: { thinking: { command: "claude" }, coding: { command: "claude" } },
  };
}

describe("buildSite", () => {
  let root: string;

  beforeEach(async () => {
    root = await mkdtemp(join(tmpdir(), "grimoire-site-"));
    await mkdir(join(root, "features", "auth"), { recursive: true });
    await mkdir(join(root, ".grimoire", "decisions"), { recursive: true });
    await mkdir(join(root, ".grimoire", "docs"), { recursive: true });
    await writeFile(join(root, "features", "example.feature"), FEATURE);
    await writeFile(join(root, "features", "auth", "login.feature"), FEATURE);
    await writeFile(join(root, ".grimoire", "decisions", "0001-use-example.md"), ACCEPTED_DECISION);
    await writeFile(join(root, ".grimoire", "decisions", "0002-try-other.md"), PROPOSED_DECISION);
    await writeFile(join(root, ".grimoire", "docs", "constraints.md"), CONSTRAINTS);
  });

  afterEach(async () => {
    await rm(root, { recursive: true, force: true });
  });

  async function build(): Promise<{ skipped: boolean }> {
    return buildSite(root, configWith("true"), OVERVIEW);
  }

  function sitePath(...parts: string[]): string {
    return join(root, ".grimoire", "site", ...parts);
  }

  it("wraps feature content in a gherkin fence with an auto-generated header", async () => {
    await build();

    const page = await readFile(sitePath("docs", "features", "example.md"), "utf-8");
    expect(page.split("\n")[0]).toMatch(/auto-generated.*do not edit/i);
    expect(page).toContain("```gherkin\n" + FEATURE + "```");
  });

  it("prepends a status chip to decision pages and preserves the MADR body", async () => {
    await build();

    const accepted = await readFile(sitePath("docs", "decisions", "0001-use-example.md"), "utf-8");
    expect(accepted).toContain('class="st-accepted"');
    expect(accepted).toContain("# Use the example approach");
    expect(accepted).toContain("## Context and Problem Statement");
    expect(accepted).toContain('Chosen option: "example", because it is illustrative.');

    const proposed = await readFile(sitePath("docs", "decisions", "0002-try-other.md"), "utf-8");
    expect(proposed).toContain('class="st-proposed"');
  });

  it("writes the overview markdown as index.md verbatim", async () => {
    await build();

    const index = await readFile(sitePath("docs", "index.md"), "utf-8");
    expect(index).toBe(OVERVIEW);
  });

  it("fills {{NAV}} with Overview, grouped Features, Decisions, and Constraints", async () => {
    await build();

    const mkdocs = await readFile(sitePath("mkdocs.yml"), "utf-8");
    expect(mkdocs).not.toContain("{{NAV}}");
    expect(mkdocs).not.toContain("{{SITE_NAME}}");

    const parsed = parseYaml(mkdocs) as {
      site_name: string;
      nav: Array<Record<string, unknown>>;
    };
    expect(parsed.site_name).toBe(basename(root));
    const titles = parsed.nav.map((entry) => Object.keys(entry)[0]);
    expect(titles).toEqual(["Overview", "Features", "Decisions", "Constraints"]);

    expect(mkdocs).toContain("Overview: index.md");
    expect(mkdocs).toContain("example: features/example.md");
    expect(mkdocs).toContain("auth:");
    expect(mkdocs).toContain("login: features/auth/login.md");
    expect(mkdocs).toContain("0001-use-example: decisions/0001-use-example.md");
    expect(mkdocs).toContain("Constraints: constraints.md");
  });

  it("returns skipped and writes nothing when no build command is configured", async () => {
    const outcome = await buildSite(root, configWith(), OVERVIEW);

    expect(outcome).toEqual({ skipped: true });
    expect(existsSync(sitePath())).toBe(false);
  });

  it("rejects with the command's stderr when the build command fails", async () => {
    await expect(
      buildSite(root, configWith("echo boom >&2; exit 1"), OVERVIEW)
    ).rejects.toThrow(/boom/);
  });

  it("gitignores the intermediates so only built output is committed", async () => {
    await build();

    const gitignore = await readFile(sitePath(".gitignore"), "utf-8");
    expect(gitignore).toContain("docs/");
    expect(gitignore).toContain("mkdocs.yml");
  });
});
