import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { copyFile, mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { basename, dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import type { GrimoireConfig } from "../utils/config.js";
import { matter } from "../utils/frontmatter.js";
import { findFiles, readFileOrNull } from "../utils/fs.js";

const execFileAsync = promisify(execFile);

const __dirname = dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = join(__dirname, "..", "..");
const SITE_TEMPLATES = join(PACKAGE_ROOT, "templates", "site");

const GENERATED_HEADER = "> Auto-generated by `grimoire docs` — do not edit.\n\n";

/**
 * Regenerate the MkDocs spec site under `.grimoire/site/` and run the
 * configured build command. Resolves `{ skipped: true }` without writing when
 * `tools.spec_site.command` is absent; rejects when the build command fails.
 *
 * @param root - project root directory
 * @param config - loaded grimoire config
 * @param overviewMarkdown - rendered overview, written verbatim as the site index
 */
export async function buildSite(
  root: string,
  config: GrimoireConfig,
  overviewMarkdown: string
): Promise<{ skipped: boolean }> {
  const command = config.tools.spec_site?.command;
  if (!command) return { skipped: true };

  const siteDir = join(root, ".grimoire", "site");
  const docsDir = join(siteDir, "docs");
  await rm(docsDir, { recursive: true, force: true });
  await mkdir(docsDir, { recursive: true });

  await writeFile(join(siteDir, ".gitignore"), "docs/\nmkdocs.yml\n");
  await writeFile(join(docsDir, "index.md"), overviewMarkdown);
  const hasFeatures = await writeFeaturesPage(root, docsDir);
  const hasDecisions = await writeDecisionsPage(root, docsDir);
  const hasConstraints = await writeConstraintsPage(root, docsDir);
  await copyAssets(docsDir);

  const nav = buildNav(hasFeatures, hasDecisions, hasConstraints);
  await writeMkdocsConfig(root, siteDir, nav);
  await runBuildCommand(command, root);
  return { skipped: false };
}

async function writeFeaturesPage(root: string, docsDir: string): Promise<boolean> {
  const featuresDir = join(root, "features");
  let files: string[];
  try {
    files = await findFiles(featuresDir, ".feature");
  } catch {
    return false;
  }

  const groups = groupFeatures(featuresDir, files);
  if (groups.size === 0) return false;

  const sections: string[] = [];
  for (const group of [...groups.keys()].sort(rootFirst)) {
    sections.push(`## ${group}\n`);
    for (const file of groups.get(group) ?? []) {
      const content = await readFile(file, "utf-8");
      const fenced = content.endsWith("\n") ? content : content + "\n";
      sections.push(`### ${basename(file, ".feature")}\n\n\`\`\`gherkin\n${fenced}\`\`\`\n`);
    }
  }
  await writeFile(join(docsDir, "features.md"), GENERATED_HEADER + sections.join("\n"));
  return true;
}

function groupFeatures(featuresDir: string, files: string[]): Map<string, string[]> {
  const groups = new Map<string, string[]>();
  for (const file of files.sort()) {
    const rel = relative(featuresDir, file);
    if (rel.split("/")[0] === "steps") continue;
    const group = rel.includes("/") ? rel.split("/")[0] : "(root)";
    groups.set(group, [...(groups.get(group) ?? []), file]);
  }
  return groups;
}

function rootFirst(a: string, b: string): number {
  if (a === "(root)") return -1;
  if (b === "(root)") return 1;
  return a.localeCompare(b);
}

async function writeDecisionsPage(root: string, docsDir: string): Promise<boolean> {
  const decisionsDir = join(root, ".grimoire", "decisions");
  let files: string[];
  try {
    const entries = await readdir(decisionsDir);
    files = entries.filter((f) => f.endsWith(".md") && f !== "template.md").sort();
  } catch {
    return false;
  }
  if (files.length === 0) return false;

  const sections: string[] = [];
  for (const file of files) {
    const { data, content } = matter(await readFile(join(decisionsDir, file), "utf-8"));
    const status = data.status ? String(data.status).trim() : "proposed";
    const chip = `<span class="st-${status.split(" ")[0].toLowerCase()}">${status}</span>`;
    const titleMatch = content.match(/^# (.+)$/m);
    const title = titleMatch ? titleMatch[1] : basename(file, ".md");
    const body = titleMatch ? content.replace(titleMatch[0], "").trimStart() : content;
    sections.push(`## ${title}\n\n${chip}\n\n${body.trimEnd()}\n`);
  }
  await writeFile(join(docsDir, "decisions.md"), GENERATED_HEADER + sections.join("\n"));
  return true;
}

async function writeConstraintsPage(root: string, docsDir: string): Promise<boolean> {
  const content = await readFileOrNull(join(root, ".grimoire", "docs", "constraints.md"));
  if (!content) return false;
  await writeFile(join(docsDir, "constraints.md"), GENERATED_HEADER + content);
  return true;
}

async function copyAssets(docsDir: string): Promise<void> {
  const assetsDir = join(docsDir, "assets");
  await mkdir(assetsDir, { recursive: true });
  await copyFile(join(SITE_TEMPLATES, "logo.png"), join(assetsDir, "logo.png"));
  await copyFile(join(SITE_TEMPLATES, "extra.css"), join(assetsDir, "extra.css"));
}

function buildNav(
  hasFeatures: boolean,
  hasDecisions: boolean,
  hasConstraints: boolean
): string {
  const lines = ["  - Overview: index.md"];
  if (hasFeatures) lines.push("  - Features: features.md");
  if (hasDecisions) lines.push("  - Decisions: decisions.md");
  if (hasConstraints) lines.push("  - Constraints: constraints.md");
  return lines.join("\n");
}

async function writeMkdocsConfig(root: string, siteDir: string, nav: string): Promise<void> {
  const template = await readFile(join(SITE_TEMPLATES, "mkdocs.yml.tpl"), "utf-8");
  const rendered = template
    .replace("{{SITE_NAME}}", basename(root))
    .replace("{{NAV}}", nav);
  await writeFile(join(siteDir, "mkdocs.yml"), rendered);
}

async function runBuildCommand(command: string, root: string): Promise<void> {
  try {
    await execFileAsync("sh", ["-c", command], { cwd: root, timeout: 300_000 });
  } catch (err) {
    const stderr =
      err && typeof err === "object" && "stderr" in err
        ? String((err as { stderr: unknown }).stderr)
        : String(err);
    throw new Error(`spec site build failed: ${command}\n${stderr}`.trim());
  }
}
