import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import type { Command } from "commander";
import { buildProgram } from "../src/cli/program.js";

// Generated CLI reference. Source of truth = the commander program in src/cli/program.ts.
// Run via `npm run docs:gen`. Do not edit the output by hand.

const here = dirname(fileURLToPath(import.meta.url));
const outFile = join(here, "..", "docs", "reference", "cli.md");

function escape(text: string): string {
  return text.replace(/\|/g, "\\|");
}

function synopsis(cmd: Command): string {
  const parts = ["grimoire", cmd.name()];
  if (cmd.options.length > 0) parts.push("[options]");
  for (const arg of cmd.registeredArguments) {
    const inner = arg.variadic ? `${arg.name()}...` : arg.name();
    parts.push(arg.required ? `<${inner}>` : `[${inner}]`);
  }
  return parts.join(" ");
}

function argsTable(cmd: Command): string {
  if (cmd.registeredArguments.length === 0) return "";
  const rows = cmd.registeredArguments.map((arg) => {
    const name = arg.variadic ? `${arg.name()}...` : arg.name();
    const required = arg.required ? "yes" : "no";
    const def = arg.defaultValue !== undefined ? `\`${JSON.stringify(arg.defaultValue)}\`` : "";
    return `| \`${name}\` | ${required} | ${escape(arg.description ?? "")} | ${def} |`;
  });
  return ["\n**Arguments**\n", "| Argument | Required | Description | Default |", "| --- | --- | --- | --- |", ...rows].join("\n") + "\n";
}

function optionsTable(cmd: Command): string {
  if (cmd.options.length === 0) return "";
  const rows = cmd.options.map((opt) => {
    const def = opt.defaultValue !== undefined ? `\`${JSON.stringify(opt.defaultValue)}\`` : "";
    return `| \`${escape(opt.flags)}\` | ${escape(opt.description ?? "")} | ${def} |`;
  });
  return ["\n**Options**\n", "| Flag | Description | Default |", "| --- | --- | --- |", ...rows].join("\n") + "\n";
}

function renderCommand(cmd: Command): string {
  const lines: string[] = [`## \`grimoire ${cmd.name()}\``, ""];
  if (cmd.description()) lines.push(cmd.description(), "");
  const aliases = cmd.aliases();
  if (aliases.length > 0) lines.push(`**Aliases:** ${aliases.map((a) => `\`${a}\``).join(", ")}`, "");
  lines.push("```", synopsis(cmd), "```");
  lines.push(argsTable(cmd));
  lines.push(optionsTable(cmd));
  return lines.join("\n");
}

function generate(): string {
  const program = buildProgram();
  const commands = [...program.commands].sort((a, b) => a.name().localeCompare(b.name()));
  const header = [
    "<!-- AUTO-GENERATED by scripts/gen-cli-docs.ts — do not edit by hand. -->",
    "",
    "# CLI reference",
    "",
    program.description() ?? "",
    "",
    "## Global",
    "",
    "```",
    "grimoire [command] [options]",
    "```",
    "",
    "| Flag | Description |",
    "| --- | --- |",
    "| `-V, --version` | Print the version number |",
    "| `-h, --help` | Print help for a command |",
    "",
  ].join("\n");
  return [header, ...commands.map(renderCommand)].join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
}

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, generate(), "utf-8");
console.log(`Wrote ${outFile}`);
